// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function BrowseFiles():Promise<Array<string>>;

export function CondenseFiles(arg1:Array<string>,arg2:main.CondenseOptions):Promise<void>;

export function GetFileName(arg1:string):Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function OpenDirectory(arg1:string):Promise<void>;

export function SelectDirectory():Promise<string>;
