// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BrowseFiles() {
  return window['go']['main']['App']['BrowseFiles']();
}

export function CondenseFiles(arg1, arg2) {
  return window['go']['main']['App']['CondenseFiles'](arg1, arg2);
}

export function GetFileName(arg1) {
  return window['go']['main']['App']['GetFileName'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function OpenDirectory(arg1) {
  return window['go']['main']['App']['OpenDirectory'](arg1);
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}
